am-api:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  applicationPort: 2703
  environment:
    AM_API_DB_HOST: localhost
    AM_API_DB_PORT: 5432
    AM_API_DB_NAME: am
    AM_API_DB_USERNAME: amuser
    AM_API_DB_PASSWORD: ampass
    ENABLE_DB_MIGRATE_IN_SERVICE: true

postgresql:
  postgresqlUsername: amuser
  postgresqlPassword: ampass
  postgresqlDatabase: am
  persistence:
    enabled: false
